# Generated by Django 2.1.3 on 2018-12-05 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20181205_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='band',
            field=models.ManyToManyField(related_name='bandas', to='events.Band'),
        ),
    ]
