# Generated by Django 2.1.3 on 2018-12-05 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_band'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='participantes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
